apiVersion: apps/v1
kind: Deployment
metadata: 
    name: frontend 
    labels:
       app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: siddheshsomvanshi27/frontendimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
